language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mdraheim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mdraheim/docker-react npm run test